name: data_science
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - beakerx
  - ipywidgets
  - r-essentials
  - beautifulsoup4
  - requests
